import { Separator } from '../ui/separator';
import { ToolsAlignCenter } from './tools-align-center';
import { ToolsAlignJustify } from './tools-align-justify';
import { ToolsAlignLeft } from './tools-align-left';
import { ToolsAlignRight } from './tools-align-right';
import { ToolsBlockquote } from './tools-blockquote';
import { ToolsBold } from './tools-bold';
import { ToolsCode } from './tools-code';
import { ToolsCodeblock } from './tools-codeblock';
import { ToolsColorSelector } from './tools-color-selector';
import { ToolsHorizontalRule } from './tools-horizontal-rule';
import { ToolsImage } from './tools-image';
import { ToolsImageAlignCenter } from './tools-image-align-center';
import { ToolsImageAlignLeft } from './tools-image-align-left';
import { ToolsImageAlignRight } from './tools-image-align-right';
import { ToolsImageFullWidth } from './tools-image-full-width';
import { ToolsImageRemove } from './tools-image-remove';
import { ToolsItalic } from './tools-italic';
import { ToolsLink } from './tools-link';
import { ToolsLists } from './tools-lists';
import { ToolsRedo } from './tools-redo';
import { ToolsStrike } from './tools-strike';
import { ToolsSubscript } from './tools-subscript';
import { ToolsSuperscript } from './tools-superscript';
import { ToolsTextBlocks } from './tools-text-blocks';
import { ToolsUnderline } from './tools-underline';
import { ToolsUndo } from './tools-undo';

export function Tools() {
  return null;
}

Tools.alignCenter = ToolsAlignCenter;
Tools.alignJustify = ToolsAlignJustify;
Tools.alignLeft = ToolsAlignLeft;
Tools.alignRight = ToolsAlignRight;
Tools.blockquote = ToolsBlockquote;
Tools.bold = ToolsBold;
Tools.code = ToolsCode;
Tools.codeblock = ToolsCodeblock;
Tools.colorSelector = ToolsColorSelector;
Tools.horizontalRule = ToolsHorizontalRule;
Tools.image = ToolsImage;
Tools.imageAlignCenter = ToolsImageAlignCenter;
Tools.imageAlignLeft = ToolsImageAlignLeft;
Tools.imageAlignRight = ToolsImageAlignRight;
Tools.imageFullWidth = ToolsImageFullWidth;
Tools.imageRemove = ToolsImageRemove;
Tools.italic = ToolsItalic;
Tools.link = ToolsLink;
Tools.lists = ToolsLists;
Tools.redo = ToolsRedo;
Tools.strike = ToolsStrike;
Tools.subscript = ToolsSubscript;
Tools.superscript = ToolsSuperscript;
Tools.textBlocks = ToolsTextBlocks;
Tools.underline = ToolsUnderline;
Tools.undo = ToolsUndo;
Tools.separator = Separator;
